# Generated by Django 2.2.7 on 2019-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingbook', '0002_auto_20191120_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
